harry:
    type: Book
    title: Harry Potter and the Order of the Phoenix
    author: [“Rowling, J. K.”]
    date: 2003-06-21

electronic:
    type: Web
    title: Ishkur’s Guide to Electronic Music
    author: Ishkur
    url: http://www.techno.org/electronic-music-guide/

kinetics:
    type: Article
    title: Kinetics and luminescence of the excitations of a nonequilibrium polariton condensate
    author: [“Doan, T. D.”, “Tran Thoai, D. B.”, “Haug, Hartmut”]
    doi: “10.1103/PhysRevB.102.165126”
    page-range: 165126-165139
    date: 2020-10-14
    parent:
        type: Periodical
        title: Physical Review B 
        olume: 102
        issue: 16
        publisher: American Physical Society

wwdc-network: 
    type: Article
    author: [“Mehta, Jiten”, “Kinnear, Eric”]
    title: Boost Performance and Security with Modern Networking
    date: 2020-06-26
    parent:
        -   type: Conference
            title: World Wide Developer Conference 2020
            organization: Apple Inc.
            location: Mountain View, CA
        -   type: Video
            runtime: 00:13:42
            url: https://developer.apple.com/videos/play/wwdc2020/10111/

plaque:
    type: Misc
    title: Informational plaque about Jacoby’s 1967 photos
    publisher: Stiftung Reinbeckhallen
    location: Berlin, Germany
    date: 2020
    parent:
        -   type: Artwork
            date: 1967
            author: Jacoby, Max
     
        -   type: Anthology
            title: Bleibtreustraße
            archive: Landesmuseum Koblenz
            archive-location: Koblenz, Germany
